apiVersion: v1
kind: Service
metadata:
name: {{ include "learnerreport.fullname" . }}-backend-svc
labels:
{{- include "learnerreport.labels" . | nindent 4 }}
spec:
type: {{ .Values.service.backend.type }}
selector:
app: {{ include "learnerreport.fullname" . }}-backend
ports:
- name: http
port: {{ .Values.service.backend.port }}
targetPort: {{ .Values.service.backend.targetPort }}
protocol: TCP