apiVersion: v1
kind: Service
metadata:
name: {{ include "learnerreport.fullname" . }}-frontend-svc
labels:
{{- include "learnerreport.labels" . | nindent 4 }}
spec:
type: {{ .Values.service.frontend.type }}
selector:
app: {{ include "learnerreport.fullname" . }}-frontend
ports:
- name: http
port: {{ .Values.service.frontend.port }}
targetPort: {{ .Values.service.frontend.targetPort }}
protocol: TCP