{{- if .Values.hpa.frontend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
name: {{ include "learnerreport.fullname" . }}-frontend
labels:
{{- include "learnerreport.labels" . | nindent 4 }}
spec:
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: {{ include "learnerreport.fullname" . }}-frontend
minReplicas: {{ .Values.hpa.frontend.minReplicas }}
maxReplicas: {{ .Values.hpa.frontend.maxReplicas }}
metrics:
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: {{ .Values.hpa.frontend.targetCPUUtilizationPercentage }}
{{- end }}