{{- if .Values.hpa.backend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
name: {{ include "learnerreport.fullname" . }}-backend
labels:
{{- include "learnerreport.labels" . | nindent 4 }}
spec:
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: {{ include "learnerreport.fullname" . }}-backend
minReplicas: {{ .Values.hpa.backend.minReplicas }}
maxReplicas: {{ .Values.hpa.backend.maxReplicas }}
metrics:
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: {{ .Values.hpa.backend.targetCPUUtilizationPercentage }}
{{- end }}