apiVersion: v1
kind: Secret
metadata:
name: {{ include "learnerreport.fullname" . }}-secrets
labels:
{{- include "learnerreport.labels" . | nindent 4 }}
type: Opaque
stringData:
mongo_uri: {{ .Values.secrets.mongoUri | quote }}