apiVersion: v1
kind: Service
metadata:
  name: learner-backend-svc
spec:
  selector:
    app: learner-backend
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  type: ClusterIP
